
LIBRARIES = unity
unity_SOURCES = src/unity.c


TESTS = test_unity 
test_unity_TESTING = unity
test_unity_UNITY = test/test_unity.c
test_unity_SOURCES = test/test_unity.c
test_unity_DEPENDS = unity

include ../../buildsys/common/rules.mk
