# @Copyright 2018 Owlstone Medical Ltd, All Rights Reserved
#
# Description: Defines global variables used by the zsys buildsystem

# The root path for the built objects built by the zsys buildsystem
BUILD_ROOT = ${ZSYS_ROOT}/build/${ZSYS_DISTRIBUTION}/${ZSYS_TARGET}

# The root path for the object files built by the zsys buildsystem
OBJECTS_ROOT = $(BUILD_ROOT)/objects

# The root path for the coverage files generated by code coverage tools
COVERAGE_ROOT = $(BUILD_ROOT)/coverage

# The root path for the libraries built by the zsys buildsystem
SHARED_LIBS_ROOT = $(BUILD_ROOT)/lib

# The root path for the public header files exported by each library built by
# the zsys buildsystem
SHARED_INCS_ROOT = $(BUILD_ROOT)/include

# The root path for the executables built by the zsys buildsystem
EXECUTABLES_ROOT = $(BUILD_ROOT)/bin

# The prefix to use when using CMOCK to auto generate mocks
CMOCK_PREFIX = mock_
